### ISSUE TITLE
Slow speed on 5GHz with T4Uv3

### ISSUE THREAD

**Issue by adrium** [cilynx/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959#24]
Hi, I tried your driver for the [TP-Link Archer T4Uv3](https://www.tp-link.com/us/home-networking/usb-adapter/archer-t4u/).

It compiles and device works of sorts. I can connect to my 5GHz network, but I get miserable speed. Sometimes less then one Mbps download. Interestingly, the upload was around 80 Mbps in one test.

I also tried to use the [official driver by TP-Link](https://www.tp-link.com/us/support/download/archer-t4u/) and applied your fixes. [Here is a repo of the merge](https://github.com/adrium/rtl88x2bu).

I played with the `rtw_power_mgnt` and `rtw_smart_ps` parameters without any luck.

The results are the same: low speeds.

Do you have any advice on improving the situation?

**Comment by Niproblema** [comment]
`/etc/NetworkManager/conf.d/default-wifi-powersave-on.conf` from 3 (enabled) to 2 (disabled).
Helps me nearly match windows drivers speed

**Comment by adrium** [comment]
Thanks, that helped!

I also tried the parameters `rtw_power_mgnt=0 rtw_ips_mode=0` which gave very good results as well.
