### ISSUE TITLE
Not working on kernel 5.3.1 on Arch Linux

### ISSUE THREAD

**Issue by Xecestel** [cilynx/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959#43]
Even though I tried uninstalling it and reinstalling them several times, the drivers are just not working anymore since the last kernel update and the WiFi dongle doesn't get recognized by the system.

**Comment by IvarWithoutBones** [comment]
Same for me.

**Comment by Xecestel** [comment]
After the last kernel update I rebuilt and reinstalled the drivers and they started working. Closing the issue.
