### ISSUE TITLE
Driver doesn't work on kernel 5.3.6 - Fedora 30

### ISSUE THREAD

**Issue by rrafal1337** [cilynx/rtl88x2BU_WiFi_linux_v5.3.1_27678.20180430_COEX20180427-5959#48]
Hi. Driver previously worked with 5.2.18. I was able to compile driver on 5.3.x but when it starts there is error in dmesg about module:
https://pastebin.com/7Vaw3dJJ

**Comment by rrafal1337** [comment]
Sister project (rtl8821cu) already have solution implemented.
Details see here: https://github.com/brektrou/rtl8821CU/issues/15#issuecomment-545037120

**Comment by cilynx** [comment]
The vendor command policy fix mentioned in that thread was merged here from #42.  We'll need to do some digging to find what's failing with the newer kernel.

**Comment by silvernode** [comment]
@cilynx Just wanted to confirm that I have no issues on Fedora 31 with kernel 5.3.6.  

`$ Linux 5.3.6-300.fc31.x86_64`  

I will be happy to provide useful information if requested. 

EDIT: Fedora 31 had an update recently to Kernel 5.3.7. I am happy to report that dkms has worked as intended and my Wireless Dongle continues to work without regression. 

By the way, the chipset I have in this Wireless Dongle is:`0bda:b812`

**Comment by fleamour** [comment]
Fedora GNOME 31:
```
Error! echo
Your kernel headers for kernel 5.3.7-301.fc31.x86_64 cannot be found at
/lib/modules/5.3.7-301.fc31.x86_64/build or /lib/modules/5.3.7-301.fc31.x86_64/source.
```

**Comment by rrafal1337** [comment]
> Fedora GNOME 31:
> 
> ```
> Error! echo
> Your kernel headers for kernel 5.3.7-301.fc31.x86_64 cannot be found at
> /lib/modules/5.3.7-301.fc31.x86_64/build or /lib/modules/5.3.7-301.fc31.x86_64/source.
> ```

Hi. You need to install dkms, kernel-devel, kernel-headers, gcc, bc packages.

I can confirm driver works for me with latest kernel on Fedora 30 - 5.3.8-200.fc30.x86_64

Thank you for support.
